version: '3.4'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${NESTJS_PORT}:${NESTJS_PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - main
    depends_on:
      - nats
  nats:
    container_name: nats
    image: synadia/nats-server:nightly
    volumes:
      - ./config/:/etc/nats
    command: '-c /etc/nats/nats.conf'
    networks:
      - main
    ports:
      - '4222:4222'
      - '8222:8222'
      - '9222:9222'
networks:
  main:
