apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iam-org-creator.fullname" . }}-configmap
  labels:
    {{- include "iam-org-creator.labels" . | nindent 4 }}
data:
  NESTJS_PORT: {{ .Values.iamOrgCreator.config.NESTJS_PORT | default "9000" | quote }}
  NATS_CLIENTS_URL: {{ .Values.iamOrgCreator.config.NATS_CLIENTS_URL | default "nats://identityevents-dev-nats.energyweb.org:4222" | quote }}
  REQUEST_NEW_ORG_ROLE: {{ .Values.iamOrgCreator.config.REQUEST_NEW_ORG_ROLE | default "orgowner.roles.orgcreator.apps.energyweb.iam.ewc" | quote }}
  VOLTA_CHAIN_ID: {{ .Values.iamOrgCreator.config.VOLTA_CHAIN_ID | default "73799" | quote }}
  CACHE_SERVER_URL: {{ .Values.iamOrgCreator.config.CACHE_SERVER_URL | default "https://identitycache-dev.energyweb.org/v1" | quote }}
  RPC_URL: {{ .Values.iamOrgCreator.config.RPC_URL | default "https://volta-rpc.energyweb.org" | quote }}
  ORG_NAMESPACE: {{ .Values.iamOrgCreator.config.ORG_NAMESPACE | default "iam.ewc" | quote }}
