name: ci

on:
  pull_request:
    branches: [ master, develop, DOI-1822_health_check]

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    services:
      jetstream:
        image: synadia/jsm:latest
        options: >-
          -e JSM_MODE=server
    steps:
      - uses: actions/checkout@v2
      - name: Setup app dependencies
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm ci
      - name: Check linting
        run: npm run lint
      - name: Audit package dependencies
        run: npm audit --audit-level=critical
      - name: Build project
        run: npm run build
      - name: Create Nats cluster
        uses: onichandame/nats-action@master
        with:
          port: '4222 4223 4224'
      - name: Run Tests
        run: npm run test  --coverage --reporters=default --reporters=jest-junit --runInBand --forceExit
