name: DEV

on:
  push:
  pull_request:
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    services:
      jetstream:
        image: synadia/jsm:latest
        options: >-
          -e JSM_MODE=server
    steps:
      - uses: actions/checkout@v2
      - name: Setup app dependencies
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm install
      - name: Check linting
        run: npm run fix:tslint
      - name: Audit package dependencies
        run: npm audit --audit-level=critical
      - name: Build project
        run: npm run build
      - name: Run Nats
        uses: nats-io/jetstream-gh-action/create/stream@main
        with:
          server: 0.0.0.0:4222
      - name: Run Tests
        run: npm run test  --coverage --reporters=default --reporters=jest-junit --runInBand --forceExit
